doc: Sync examples with lxc-ci definitions
Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

diff --git a/doc/examples/debian-cloud-init b/doc/examples/debian-cloud-init
--- a/doc/examples/debian-cloud-init
+++ b/doc/examples/debian-cloud-init
@@ -6,11 +6,17 @@ image:
 
 source:
   downloader: debootstrap
+  apt_sources: |-
+    deb http://deb.debian.org/debian {{ image.release }} main
+    {% if image.release != "sid" and image.release != "buster" and not (image.release == "wheezy" and image.architecture_mapped == "powerpc") and not (image.release == "wheezy" and image.architecture_mapped == "s390x") %}deb http://security.debian.org/debian-security {{ image.release }}/updates main{% endif %}
 
 targets:
   lxc:
-    create-message: |
-        You just created a Debian container (release={{ image.release }}, arch={{ image.architecture }}, variant={{ image.variant }})
+    create-message: |-
+      You just created a {{ image.description }} container.
+
+      To enable SSH, run: apt install openssh-server
+      No default root or user password are set by LXC.
 
     config:
       - type: all
@@ -35,111 +41,91 @@ targets:
 
       - type: all
         content: |-
-          lxc.arch = {{ image.architecture_kernel }}
+          lxc.arch = {{ image.architecture_personality }}
 
 files:
-  - name: interfaces
-    generator: dump
-    path: /etc/network/interfaces
-    content: |
-      # interfaces(5) file used by ifup(8) and ifdown(8)
-      # Include files from /etc/network/interfaces.d:
-      source-directory /etc/network/interfaces.d
-      source /etc/network/interfaces.d/50-cloud-init.cfg
+ - path: /etc/hostname
+   generator: hostname
 
-  - name: hostname
-    path: /etc/hostname
-    generator: hostname
+ - path: /etc/hosts
+   generator: hosts
 
-  - name: hosts
-    path: /etc/hosts
-    generator: hosts
-  - path: /etc/resolvconf/resolv.conf.d/original
-    generator: remove
+ - path: /etc/resolvconf/resolv.conf.d/original
+   generator: remove
 
-  - path: /etc/resolvconf/resolv.conf.d/tail
-    generator: remove
+ - path: /etc/resolvconf/resolv.conf.d/tail
+   generator: remove
 
-  - path: /etc/machine-id
-    generator: remove
+ - path: /etc/machine-id
+   generator: remove
 
-  - name: cloud-init-meta
-    path: /var/lib/cloud/seed/nocloud-net/meta-data
-    generator: template
-    template:
-      when:
-        - create
-        - copy
-    content: |
-      #cloud-config
-      instance-id: {{ container.name }}
-      local-hostname: {{ container.name }}
-      {{ config_get("user.meta-data", "") }}
+ - path: /etc/network/interfaces
+   generator: dump
+   content: |-
+     # This file describes the network interfaces available on your system
+     # and how to activate them. For more information, see interfaces(5).
 
-  - name: cloud-init-network
-    path: /var/lib/cloud/seed/nocloud-net/network-config
-    generator: template
-    template:
-      when:
-        - create
-        - copy
-    content: |
-      {% if config_get("user.network-config", "") == "" %}version: 1
-      config:
-         - type: physical
-           name: eth0
-           subnets:
-               - type: {% if config_get("user.network_mode", "") == "link-local" %}manual{% else %}dhcp{% endif %}
-                 control: auto{% else %}{{ config_get("user.network-config", "") }}{% endif %}
+     # The loopback network interface
+     auto lo
+     iface lo inet loopback
 
-  - name: cloud-init-user-data
-    path: /var/lib/cloud/seed/nocloud-net/user-data
-    generator: template
-    content: '{{ config_get("user.user-data", properties.default) }}'
-    template:
-      properties:
-        default: |
-          #cloud-config
-          {}
-      when:
-        - create
-        - copy
-
-  - name: cloud-init-vedor-data
-    path: /var/lib/cloud/seed/nocloud-net/vendor-data
-    generator: template
-    content: '{{ config_get("user.vendor-data", properties.default) }}'
-    template:
-      properties:
-        default: |
-          #cloud-config
-          {}
-      when:
-        - create
-        - copy
+     auto eth0
+     iface eth0 inet dhcp
 
 packages:
-    manager: apt
+  manager: apt
+  update: true
+  cleanup: true
 
-    update: true
-    cleanup: true
+  sets:
+    - packages:
+      - dialog
+      - ifupdown
+      - isc-dhcp-client
+      - locales
+      - netbase
+      - net-tools
+      - openssh-client
+      - vim
+      action: install
 
-    sets:
-      - packages:
-          - systemd
-          - dialog
-          - ifupdown
-          - locales
-          - netbase
-          - net-tools
-          - cloud-init
-          - cloud-utils
-          - sudo
-          - adduser
-          - locales
-          - file
-          - openssh-server
-        action: install
+actions:
+  - trigger: post-packages
+    action: |-
+      #!/bin/sh
+      set -eux
+
+      # Make sure the locale is built and functional
+      echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
+      locale-gen en_US.UTF-8 UTF-8
+      update-locale LANG=en_US.UTF-8
+
+      # Cleanup underlying /run
+      mount -o bind / /mnt
+      rm -rf /mnt/run/*
+      umount /mnt
+
+      # Cleanup temporary shadow paths
+      rm /etc/*-
+
+  - trigger: post-packages
+    action: |-
+      #!/bin/sh
+      set -eux
+      apt-get install iproute sysvinit -y
+    releases:
+      - wheezy
+
+  - trigger: post-packages
+    action: |-
+      #!/bin/sh
+      set -eux
+      apt-get install iproute2 init -y
+    releases:
+      - jessie
+      - stretch
+      - buster
+      - sid
 
 mappings:
   architecture_map: debian
